server:
  port: ${SN_NOTIFICATIONS_PORT}
  api:
    prefix: /api/v1

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://${SN_DB_HOST}:${SN_DB_PORT}/${SN_DB_NAME}
    username: ${SN_DB_USER}
    password: ${SN_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  messages:
    basename: lang/messages

  mail:
    host: ${SN_SMTP_HOST}
    port: ${SN_SMTP_PORT}
    username: ${SN_SMTP_USERNAME}
    password: ${SN_SMTP_PASSWORD}

  kafka:
    notification-serv: ${SN_NOTIFICATION_SERV}
    notification-event: ${SN_NOTIFICATION_EVENT}
    bootstrap-servers: ${SN_KAFKA_HOST}:${SN_KAFKA_PORT}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: ru.itgroup.intouch.serialization.CustomSerializer
    consumer:
      group-id: notification_serv
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: ru.itgroup.intouch.serialization.CustomDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

aggregator:
  protocol: ${SN_AGGREGATOR_PROTOCOL}
  host: ${SN_AGGREGATOR_HOST}
  port: ${SN_AGGREGATOR_PORT}

jooq:
  generator:
    database:
      name: org.jooq.meta.postgres.PostgresDatabase
      with-includes: .*
      with-input-schema: public

    target:
      package-name: ru.itgroup.intouch
      directory: notification-service/main/target/generated-sources/jooq
